# Generated by Django 5.2.9 on 2025-12-15 04:57

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Líder'), ('member', 'Integrante')], default='member', max_length=10, verbose_name='rol')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de unión')),
            ],
            options={
                'verbose_name': 'membresía',
                'verbose_name_plural': 'membresías',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('general_objectives', models.TextField(verbose_name='objetivos generales')),
                ('specific_objectives', models.TextField(verbose_name='objetivos específicos')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de fin')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=10, verbose_name='prioridad')),
                ('code', models.CharField(default=projects.models.generate_project_code, max_length=6, unique=True, verbose_name='código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
