# Generated by Django 5.2.9 on 2025-12-17 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='nombre')),
                ('room_type', models.CharField(choices=[('group', 'Grupal'), ('private', 'Privado')], default='group', max_length=10, verbose_name='tipo de sala')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('participants', models.ManyToManyField(blank=True, related_name='private_chats', to=settings.AUTH_USER_MODEL, verbose_name='participantes')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'sala de chat',
                'verbose_name_plural': 'salas de chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenido')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('file', 'Archivo'), ('image', 'Imagen'), ('system', 'Sistema')], default='text', max_length=10, verbose_name='tipo de mensaje')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/%d/', verbose_name='archivo')),
                ('is_read', models.BooleanField(default=False, verbose_name='leído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='sala de chat')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='remitente')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de lectura')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='chat.message', verbose_name='mensaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'lectura de mensaje',
                'verbose_name_plural': 'lecturas de mensajes',
                'unique_together': {('message', 'user')},
            },
        ),
    ]
